# Form implementation generated from reading ui file 'Interfaz.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.BT_abrir_clientes = QtWidgets.QPushButton(parent=self.centralwidget)
        self.BT_abrir_clientes.setGeometry(QtCore.QRect(30, 30, 111, 34))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.BT_abrir_clientes.setFont(font)
        self.BT_abrir_clientes.setObjectName("BT_abrir_clientes")
        self.BT_abrir_vehiculos = QtWidgets.QPushButton(parent=self.centralwidget)
        self.BT_abrir_vehiculos.setGeometry(QtCore.QRect(160, 30, 111, 34))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.BT_abrir_vehiculos.setFont(font)
        self.BT_abrir_vehiculos.setObjectName("BT_abrir_vehiculos")
        self.BT_abrir_rutas = QtWidgets.QPushButton(parent=self.centralwidget)
        self.BT_abrir_rutas.setGeometry(QtCore.QRect(290, 30, 111, 34))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.BT_abrir_rutas.setFont(font)
        self.BT_abrir_rutas.setObjectName("BT_abrir_rutas")
        self.text_area = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.text_area.setGeometry(QtCore.QRect(110, 150, 541, 221))
        self.text_area.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.text_area.setObjectName("text_area")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.BT_abrir_clientes.setText(_translate("MainWindow", "Abrir_Clientes"))
        self.BT_abrir_vehiculos.setText(_translate("MainWindow", "Abrir_Vehiculos"))
        self.BT_abrir_rutas.setText(_translate("MainWindow", "Abrir_Rutas"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
